### ISSUE TITLE
Create version compatible with Python 3.4 and under

### ISSUE THREAD

**Issue by flashmeow** [LordFlashmeow/pycent#7]
The `typing` module is new in Python 3.5.
Can / should we make a version for Python 3.4 and under?

**Comment by TurnrDev** [comment]
Oh, I didn't know typing was Python 3.5. We can probably scrap that. Type hinting isn't vital if we specify in the docs what types of data it accepts at inputs clearly in the docs.

**Comment by flashmeow** [comment]
PR #8 has solved this issue
